prometheus:
  server:
    global:
      scrape_interval: 15s
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

grafana:
  adminPassword: "admin123"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.skyshop.example.com
  persistence:
    enabled: true
    size: 10Gi
