apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ "{{ include \"database.fullname\" . }}" }}
spec:
  replicas: {{ "{{ .Values.replicaCount }}" }}
  selector:
    matchLabels:
      app: {{ "{{ include \"database.name\" . }}" }}
  template:
    metadata:
      labels:
        app: {{ "{{ include \"database.name\" . }}" }}
    spec:
      containers:
        - name: postgres
          image: "{{ "{{ .Values.image.repository }}:{{ .Values.image.tag }}" }}"
          ports:
            - containerPort: {{ "{{ .Values.service.port }}" }}
          env:
            - name: POSTGRES_DB
              value: {{ "{{ .Values.postgresql.postgresDb }}" }}
            - name: POSTGRES_USER
              value: {{ "{{ .Values.postgresql.postgresUser }}" }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ "{{ include \"database.fullname\" . }}-secret" }}
                  key: postgres-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ "{{ include \"database.fullname\" . }}-pvc" }}
