apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ "{{ include \"database.fullname\" . }}-pvc" }}
spec:
  accessModes:
    - {{ "{{ .Values.persistence.accessMode }}" }}
  resources:
    requests:
      storage: {{ "{{ .Values.persistence.size }}" }}
  storageClassName: {{ "{{ .Values.persistence.storageClass }}" }}
