name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Add Helm repository
      run: |
        helm repo add stable https://charts.helm.sh/stable

    - name: Install dependencies
      run: |
        helm dependency update global-e-commerce-platform/helm-charts/monitoring

    - name: Lint Helm chart
      run: |
        helm lint global-e-commerce-platform/helm-charts/monitoring

    - name: Package Helm chart
      run: |
        helm package global-e-commerce-platform/helm-charts/monitoring -d helm-charts/monitoring/charts/

    - name: Set Kubernetes context
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy Helm chart to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: ./helm-charts/monitoring/dist/
        action: deploy
