name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'

    - name: Install dependencies
      run: |
        helm dependency update global-e-commerce-platform/helm-charts/monitoring

    - name: Lint Helm chart
      run: |
        helm lint global-e-commerce-platform/helm-charts/monitoring

    - name: Package Helm chart
      run: |
        helm package global-e-commerce-platform/helm-charts/monitoring -d helm-charts/monitoring/dist

    - name: Deploy Helm chart to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        namespace: default
        manifests: global-e-commerce-platform/helm-charts/monitoring/dist/*.tgz

